version: "3.9"
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/anatomy
      - SYNC_DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/anatomy
      - SECRET_KEY=change-me
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_MINUTES=4320
      - JWT_ALGORITHM=HS256
      - REDIS_URL=redis://redis:6379/0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - FEATURE_FLAG_OSCE=true
      - FEATURE_FLAG_SRS=true
      - RATE_LIMIT_PER_MINUTE=120
      - DEFAULT_PAGE_SIZE=20
      - MAX_PAGE_SIZE=100
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
      - otel-collector

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: anatomy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector:0.94.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"

volumes:
  pgdata:
